version: "3.9"
services:
  rstudio:
    build: .
    # add the image name of your container
    image: qbicprojects/rstudio-template:latest
    ulimits:
      nofile: 10000
    ports:
        - "8889:8787"
    volumes:
      # mount conda env into exactly the same path as on the host system - some paths are hardcoded in the env.
      - /home/centos/anaconda3/envs/R400:/home/centos/anaconda3/envs/R400
      # Share settings between rstudio instances
      - /home/centos/.local/share/rstudio/monitored/user-settings:/root/.local/share/rstudio/monitored/user-settings
      # mount the working directory containing your R project.
      - /home/centos/projects:/root/projects
    environment:
      - PASSWORD=notsafe
      # repeat the path of the conda environment
      - CONDAENV=/home/sturm/anaconda3/envs/R400